language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
  
script: 
  - pytest --cov=./
    
after_success:
  - codecov

branches:
  only:
  - master
