language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  
script: 
  - pytest
  - coverage run tests/test_task.py
 
after_success:
  - codecov

branches:
  only:
  - master
