language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  
script: 
  - pytest

after_script:
  - coveralls
 
after_success:
  - codecov

branches:
  only:
  - master
