apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flasky-deployment
  labels:
    app: flasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flasky
  template:
    metadata:
      labels:
        app: flasky
    spec:
      containers:
      - name: flasky
        image: gmarciani/flasky:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000