apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasky-deployment
  labels:
    app: flasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasky
  template:
    metadata:
      labels:
        app: flasky
    spec:
      containers:
      - name: flasky
        image: gmarciani/flasky:latest
        ports:
        - containerPort: 8000
