apiVersion: v1
kind: Service
metadata:
  name: flasky-service
  labels:
    app: flasky
spec:
  selector:
    app: flasky
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000